# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: pass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  mail:
    host: smtp.gmail.com
    port: 587
    username: shahbajshaikh.ss95@gmail.com
    password: xxnm kzyn ywfh ubvk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  messages:
    invalidLogin: Invalid Credentials
    invalidPwds: Both pwds should be match
    pwdUpdatedFailed: Pwd update failed
    regSuccess: Registration successful
    regFailure: Registration Failed
    quoteEndpointUrl: https://type.fit/api/quotes
    regEmailSubject: Your Account Created - Ashok IT